server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: kaz-patent-sso
            client-secret: kaz-patent-sso-secret
            authorization-grant-type: kaz-patent-sso-password
            scope: openid

        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/my-realm
            user-name-attribute: preferred_username